### ISSUE TITLE
Superfluid doesn't support inflationary tokens

### ISSUE THREAD

**Issue by jamalavedra** [markcarey/degendogs#1]
Because Superfluid doesn't support inflationary tokens, the interest gained from Compound will be lost.

**Comment by markcarey** [comment]
The Compound cTokens are not inflationary. Rather they rely on an exchange rate at redemption time. Details at https://compound.finance/docs/ctokens

(As a side note, Degen Dogs will not be using Compound for its upcoming launch, since Compound is not on Polygon)

**Comment by jamalavedra** [comment]
Got it! Thanks.

I'm working on doing something similar with Polygon and was going with Aave for this. Found the issue that aTokens are inflationary and thought cTokens would be too. Still trying to figure it out myself.

**Comment by markcarey** [comment]
Yes, when I switched gears from Compound, I ran into the same thing when I tried Aave ;)
